CLASS zcl_carga_datos_mmn DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_carga_datos_mmn IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.

  "----------------------------------------------------------
      DATA LS_CENTROS TYPE ZCENTRO_HOSP_MMN.

      LS_CENTROS-ID_CENTRO = 1.
      LS_CENTROS-NOMBRE_CENTRO = 'EL CAÑAL'.
      LS_CENTROS-PROVINCIA = 'MADRID'.
      LS_CENTROS-POBLACION = 'LAS MUSAS'.
      LS_CENTROS-EMAIL_CENTRO = 'WWW.ELCAÑAL@GMAIL.COM'.
      insert into ZCENTRO_HOSP_MMN VALUES @LS_CENTROS.

      LS_CENTROS-ID_CENTRO = 2.
      LS_CENTROS-NOMBRE_CENTRO = 'LA PARCA'.
      LS_CENTROS-PROVINCIA = 'VALLADOLID'.
      LS_CENTROS-POBLACION = 'LAS TRUCHAS'.
      LS_CENTROS-EMAIL_CENTRO = 'WWW.LAPARCA.COM'.
      insert into ZCENTRO_HOSP_MMN VALUES @LS_CENTROS.

      LS_CENTROS-ID_CENTRO = 3.
      LS_CENTROS-NOMBRE_CENTRO = 'SANTA MORCILLA'.
      LS_CENTROS-PROVINCIA = 'BURGOS'.
      LS_CENTROS-POBLACION = 'VEGA MORCILLA'.
      LS_CENTROS-EMAIL_CENTRO = 'WWW.SANTAMORCILLA.COM'.
      insert into ZCENTRO_HOSP_MMN VALUES @LS_CENTROS.

      LS_CENTROS-ID_CENTRO = 4.
      LS_CENTROS-NOMBRE_CENTRO = 'HOSPITEN'.
      LS_CENTROS-PROVINCIA = 'MADRID'.
      LS_CENTROS-POBLACION = 'VALLECAS'.
      LS_CENTROS-EMAIL_CENTRO = 'WWW.HOSPITEN.COM'.
      insert into ZCENTRO_HOSP_MMN VALUES @LS_CENTROS.

      LS_CENTROS-ID_CENTRO = 5.
      LS_CENTROS-NOMBRE_CENTRO = 'CLINICA CEMTRO'.
      LS_CENTROS-PROVINCIA = 'BARCELONA'.
      LS_CENTROS-POBLACION = 'CAMBRILLS'.
      LS_CENTROS-EMAIL_CENTRO = 'WWW.CLINICACEMTROCOM'.
      insert into ZCENTRO_HOSP_MMN VALUES @LS_CENTROS.

        DATA LS_PACIENTES TYPE zpaciente_mmn.

      LS_PACIENTES-ID_PACIENTE = 1.
      LS_PACIENTES-ID_CENTRO = 2.
      LS_PACIENTES-NOMBRE_PACIENTE = 'JOE'.
      LS_PACIENTES-APELLIDO_PACIENTE = 'EL CARNICERO'.
      LS_PACIENTES-PROVINCIA = 'CUENCA'.
      LS_PACIENTES-POBLACION = 'BETETA'.
      LS_PACIENTES-EMAIL_PACIENTE = 'WWW.JOEELCARNICERO@GMAIL.COM'.
      LS_PACIENTES-TELEFONO = '111222333'.
      insert into zpaciente_mmn VALUES @LS_PACIENTES.

      LS_PACIENTES-ID_PACIENTE = 2.
      LS_PACIENTES-ID_CENTRO = 4.
      LS_PACIENTES-NOMBRE_PACIENTE = 'HANNA'.
      LS_PACIENTES-APELLIDO_PACIENTE = 'LA PESCADERA'.
      LS_PACIENTES-PROVINCIA = 'VALLADOLID'.
      LS_PACIENTES-POBLACION = 'MORCON'.
      LS_PACIENTES-EMAIL_PACIENTE = 'WWW.HANNALAPESCADERA@GMAIL.COM'.
      LS_PACIENTES-TELEFONO = '222333444'.
      insert into zpaciente_mmn VALUES @LS_PACIENTES.

      LS_PACIENTES-ID_PACIENTE = 3.
      LS_PACIENTES-ID_CENTRO = 2.
      LS_PACIENTES-NOMBRE_PACIENTE = 'JHONAS'.
      LS_PACIENTES-APELLIDO_PACIENTE = 'EL TURBINAS'.
      LS_PACIENTES-PROVINCIA = 'BURGOS'.
      LS_PACIENTES-POBLACION = 'MORCILLAS'.
      LS_PACIENTES-EMAIL_PACIENTE = 'WWW.ELTURBINAS@GMAIL.COM'.
      LS_PACIENTES-TELEFONO = '333444555'.
      insert into zpaciente_mmn VALUES @LS_PACIENTES.

      LS_PACIENTES-ID_PACIENTE = 4.
      LS_PACIENTES-ID_CENTRO = 1.
      LS_PACIENTES-NOMBRE_PACIENTE = 'S'.
      LS_PACIENTES-APELLIDO_PACIENTE = 'EL DROGAS'.
      LS_PACIENTES-PROVINCIA = 'MADRID'.
      LS_PACIENTES-POBLACION = 'PITIS'.
      LS_PACIENTES-EMAIL_PACIENTE = 'WWW.ELDROGAS@GMAIL.COM'.
      LS_PACIENTES-TELEFONO = '444555666'.
      insert into zpaciente_mmn VALUES @LS_PACIENTES.

      LS_PACIENTES-ID_PACIENTE = 5.
      LS_PACIENTES-ID_CENTRO = 5.
      LS_PACIENTES-NOMBRE_PACIENTE = 'PEPA'.
      LS_PACIENTES-APELLIDO_PACIENTE = 'LA CERDA'.
      LS_PACIENTES-PROVINCIA = 'BARCELONA'.
      LS_PACIENTES-POBLACION = 'LAS RAMBLAS'.
      LS_PACIENTES-EMAIL_PACIENTE = 'WWW.PEPALACERDA@GMAIL.COM'.
      LS_PACIENTES-TELEFONO = '444555666'.
      insert into zpaciente_mmn VALUES @LS_PACIENTES.

      if sy-subrc EQ 0.
        out->write( 'se ha insertado correctamente' ).
      endif.
  ENDMETHOD.
ENDCLASS.
